# Generated by Django 2.0.1 on 2020-08-18 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='资讯名')),
                ('detail', models.TextField(verbose_name='资讯详情')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('if_toutiao', models.BooleanField(default=False, verbose_name='是否是头条')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('pic', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='主图')),
                ('pubDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '平台新闻',
                'verbose_name_plural': '平台新闻',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(default='', max_length=20, verbose_name='主菜单')),
                ('tab2', models.CharField(default='', max_length=20, verbose_name='分菜单')),
                ('title', models.CharField(default='', max_length=100, verbose_name='图表名')),
                ('data', models.TextField(default='', verbose_name='图表数据')),
                ('type', models.CharField(choices=[('pie', '饼状图'), ('bar', '柱状图'), ('bar2', '横向柱状图'), ('line', '折线图'), ('map', '地图')], default='pie', max_length=100, verbose_name='图表类型')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '图表信息',
                'verbose_name_plural': '图表信息',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('if_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='政策名')),
                ('policy_id', models.CharField(default='', max_length=20, verbose_name='政策ID')),
                ('info', models.TextField(verbose_name='政策详情')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('pubDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '政策信息',
                'verbose_name_plural': '政策信息',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='行政名称')),
                ('main', models.CharField(choices=[('0', '中央'), ('1', '北京'), ('2', '天津'), ('3', '河北省')], default='0', max_length=100, null=True, verbose_name='上级名称')),
                ('if_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '行政级别',
                'verbose_name_plural': '行政级别',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Province', verbose_name='所属行政'),
        ),
        migrations.AddField(
            model_name='policy',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Department', verbose_name='所属部门'),
        ),
    ]
