# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u90e8\u95e8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u653f\u7b56\u540d')),
                ('detail', models.TextField(verbose_name='\u653f\u7b56\u8be6\u60c5')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u653f\u7b56\u4fe1\u606f',
                'verbose_name_plural': '\u653f\u7b56\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u884c\u653f\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7701\u4efd',
                'verbose_name_plural': '\u7701\u4efd',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Province', verbose_name='\u6240\u5c5e\u884c\u653f'),
        ),
        migrations.AddField(
            model_name='department',
            name='Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Province', verbose_name='\u6240\u5c5e\u884c\u653f'),
        ),
    ]
