# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u54a8\u8baf\u540d')),
                ('detail', models.TextField(verbose_name='\u54a8\u8baf\u8be6\u60c5')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('if_show', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u54a8\u8be2\u4fe1\u606f',
                'verbose_name_plural': '\u54a8\u8be2\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u56fe\u8868\u540d')),
                ('data', models.TextField(verbose_name='\u56fe\u8868\u6570\u636e')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u56fe\u8868\u4fe1\u606f',
                'verbose_name_plural': '\u56fe\u8868\u4fe1\u606f',
            },
        ),
    ]
