# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-21 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20181021_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='add_time',
        ),
    ]
