# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_auto_20181022_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u5934\u6761\u4fe1\u606f', 'verbose_name_plural': '\u5934\u6761\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='banner',
            name='if_toutiao',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u5934\u6761'),
        ),
        migrations.AddField(
            model_name='banner',
            name='pic',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u4e3b\u56fe'),
        ),
    ]
