# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_auto_20181022_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f'),
        ),
    ]
