# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_auto_20181023_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='click_num',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='fav_num',
        ),
    ]
