# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20181023_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='chart',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='chart',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570'),
        ),
    ]
