# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('pie', '\u997c\u72b6\u56fe'), ('bar', '\u67f1\u72b6\u56fe'), ('line', '\u6298\u7ebf\u56fe'), ('map', '\u5730\u56fe')], default='pie', max_length=100, verbose_name='\u56fe\u8868\u7c7b\u578b'),
        ),
    ]
