# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0012_auto_20181023_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='main',
            field=models.CharField(choices=[('0', '\u4e2d\u592e'), ('1', '\u5317\u4eac'), ('2', '\u5929\u6d25'), ('3', '\u6cb3\u5317\u7701')], default='0', max_length=100, null=True, verbose_name='\u4e0a\u7ea7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('pie', '\u997c\u72b6\u56fe'), ('bar', '\u67f1\u72b6\u56fe'), ('bar2', '\u6a2a\u5411\u67f1\u72b6\u56fe'), ('line', '\u6298\u7ebf\u56fe'), ('map', '\u5730\u56fe')], default='pie', max_length=100, verbose_name='\u56fe\u8868\u7c7b\u578b'),
        ),
    ]
