# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_auto_20181025_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.RemoveField(
            model_name='province',
            name='main',
        ),
    ]
