# Generated by Django 2.0.1 on 2019-01-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_auto_20181025_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '平台新闻', 'verbose_name_plural': '平台新闻'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='detail',
            field=models.TextField(verbose_name='资讯详情'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='资讯名'),
        ),
    ]
