# Generated by Django 2.0.1 on 2020-08-18 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSDPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利编码')),
                ('tic', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标题-中文')),
                ('tie', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='标题-英文')),
                ('tio', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标题-原始')),
                ('ano', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请号-原始')),
                ('ad', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请日')),
                ('pd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='公开日')),
                ('pK', models.CharField(blank=True, db_column='pk', default='', max_length=50, null=True, verbose_name='文献类型')),
                ('pno', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='文献号-原始')),
                ('apo', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请人-原始')),
                ('ape', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='申请人-英文')),
                ('apc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请人-中文')),
                ('ipc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='IPC')),
                ('lc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='洛迦诺分类')),
                ('vu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利强度')),
                ('abso', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='摘要-原始语种')),
                ('abse', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='摘要-英文')),
                ('absc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='摘要-中文')),
                ('imgtitle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缩略图')),
                ('imgname', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='缩略图名称')),
                ('category', models.CharField(blank=True, choices=[('0', '未分类'), ('1', '太赫兹'), ('2', '遥感成像'), ('3', '高可靠嵌入式'), ('4', '智能识别'), ('5', '化学化工'), ('6', '新能源'), ('7', '机械'), ('8', '环保和资源'), ('9', '交通运输'), ('10', '橡胶塑料'), ('11', '仪器仪表'), ('12', '新型材料'), ('13', '电子信息'), ('14', '医药与医疗'), ('15', '农林牧业'), ('16', '海洋开发'), ('17', '航空航天'), ('18', '采矿治金'), ('19', '电气自动化'), ('20', '包装印刷'), ('21', '教育休闲'), ('22', '钒钛产业'), ('23', '安全防护')], default='0', max_length=20, null=True, verbose_name='行业分类')),
                ('lssc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='当前权利状态')),
                ('pdt', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利类型')),
                ('debec', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-中文')),
                ('debeo', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-原始')),
                ('debee', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-英文')),
                ('depc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-英文')),
                ('imgo', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='原始图')),
                ('absoimgpath', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='摘要图')),
                ('pdfexist', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='是否存在PDF')),
                ('ans', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请号标准')),
                ('pns', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='公布号标准')),
                ('sfpns', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代表性文献号')),
                ('inc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-中文')),
                ('ine', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-英文')),
                ('ino', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-原文')),
                ('agc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代理人-中文')),
                ('age', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='代理人-英文')),
                ('ago', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代理人-原文')),
                ('asc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利权人-中文')),
                ('ase', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='专利权人-英文')),
                ('aso', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利权人-原文')),
                ('exc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='审查员-中文')),
                ('exe', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='审查员人-英文')),
                ('exo', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='审查员-原文')),
                ('pdf', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='pdf地址')),
                ('cro', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='cro')),
                ('cre', models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='cre')),
                ('crc', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='crc')),
                ('cri', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='cri')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('bargain', models.BooleanField(default=True, verbose_name='议价')),
                ('if_success', models.BooleanField(default=False, verbose_name='是否为成功案例')),
                ('shop_status', models.CharField(choices=[('-1', '已下架'), ('0', '审核中'), ('1', '已上架'), ('2', '交易中'), ('3', '已交易')], default='1', max_length=20, verbose_name='上架状态')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('note', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='审核意见')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '专利商品信息',
                'verbose_name_plural': '专利商品信息',
            },
        ),
    ]
