# Generated by Django 2.0.1 on 2020-08-03 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSDPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利编码')),
                ('tic', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标题-中文')),
                ('tie', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标题-英文')),
                ('tio', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标题-原始')),
                ('ano', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请号-原始')),
                ('ad', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请日')),
                ('pd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='公开日')),
                ('pK', models.CharField(blank=True, db_column='pk', default='', max_length=50, null=True, verbose_name='文献类型')),
                ('pno', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='文献号-原始')),
                ('apo', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请人-原始')),
                ('ape', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请人-英文')),
                ('apc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请人-中文')),
                ('ipc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='IPC')),
                ('lc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='洛迦诺分类')),
                ('vu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利强度')),
                ('abso', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='摘要-原始语种')),
                ('abse', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='摘要-英文')),
                ('absc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='摘要-中文')),
                ('imgtitle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缩略图')),
                ('imgname', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缩略图名称')),
                ('lssc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='当前权利状态')),
                ('pdt', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利类型')),
                ('debec', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-中文')),
                ('debeo', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-原始')),
                ('debee', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-英文')),
                ('depc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='简要说明-英文')),
                ('imgo', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='原始图')),
                ('absoimgpath', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='摘要图')),
                ('pdfexist', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='是否存在PDF')),
                ('ans', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='申请号标准')),
                ('pns', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='公布号标准')),
                ('sfpns', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代表性文献号')),
                ('inc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='发明人-中文')),
                ('ine', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='发明人-英文')),
                ('ino', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='发明人-原文')),
                ('agc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代理人-中文')),
                ('age', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代理人-英文')),
                ('ago', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='代理人-原文')),
                ('asc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利权人-中文')),
                ('ase', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利权人-英文')),
                ('aso', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='专利权人-原文')),
                ('exc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='审查员-中文')),
                ('exe', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='审查员人-英文')),
                ('exo', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='审查员-原文')),
                ('pdf', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='pdf地址')),
                ('cro', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='cro')),
                ('cre', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='cre')),
                ('crc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='crc')),
                ('cri', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='cri')),
                ('shop_status', models.CharField(choices=[('-1', '已下架'), ('0', '审核中'), ('1', '已上架'), ('2', '交易中'), ('3', '已交易')], default='1', max_length=20, verbose_name='上架状态')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('note', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='审核意见')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '专利商品信息',
                'verbose_name_plural': '专利商品信息',
            },
        ),
    ]
