# Generated by Django 2.0.1 on 2020-08-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssdpatent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='seller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
