# Generated by Django 2.0.1 on 2020-08-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='imgname',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='缩略图名称'),
        ),
    ]
