# Generated by Django 2.0.1 on 2020-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0002_auto_20200803_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='ine',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-英文'),
        ),
    ]
