# Generated by Django 2.0.1 on 2020-08-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0002_ssdpatent_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssdpatent',
            name='category',
        ),
    ]
