# Generated by Django 2.0.1 on 2020-08-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0003_auto_20200803_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='age',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='代理人-英文'),
        ),
    ]
