# Generated by Django 2.0.1 on 2020-08-03 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0004_auto_20200803_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='seller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
