# Generated by Django 2.0.1 on 2020-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0005_auto_20200803_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='tie',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='标题-英文'),
        ),
    ]
