# Generated by Django 2.0.1 on 2020-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0006_auto_20200803_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='abse',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='摘要-英文'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='ape',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='申请人-英文'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='ase',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='专利权人-英文'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='exe',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='审查员人-英文'),
        ),
    ]
