# Generated by Django 2.0.1 on 2020-08-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0008_auto_20200803_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='ipc',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='IPC'),
        ),
    ]
