# Generated by Django 2.0.1 on 2020-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0010_auto_20200803_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='crc',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='crc'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='cre',
            field=models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='cre'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='cri',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='cri'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='cro',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='cro'),
        ),
    ]
