# Generated by Django 2.0.1 on 2020-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0011_auto_20200803_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='inc',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-中文'),
        ),
    ]
