# Generated by Django 2.0.1 on 2020-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0012_auto_20200803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssdpatent',
            name='ino',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发明人-原文'),
        ),
    ]
