# Generated by Django 2.0.1 on 2020-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0013_auto_20200803_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='bargain',
            field=models.BooleanField(default=True, verbose_name='议价'),
        ),
        migrations.AddField(
            model_name='ssdpatent',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
