# Generated by Django 2.0.1 on 2020-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0014_auto_20200807_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='if_success',
            field=models.BooleanField(default=False, verbose_name='是否为成功案例'),
        ),
    ]
