# Generated by Django 2.0.1 on 2020-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0015_ssdpatent_if_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='add',
            field=models.DateTimeField(blank=True, null=True, verbose_name='add日期'),
        ),
        migrations.AddField(
            model_name='ssdpatent',
            name='imgnamee',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='imgnamee'),
        ),
        migrations.AddField(
            model_name='ssdpatent',
            name='imgoo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='imgoo'),
        ),
        migrations.AddField(
            model_name='ssdpatent',
            name='pdd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pdd日期'),
        ),
        migrations.AddField(
            model_name='ssdpatent',
            name='pdff',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m', verbose_name='pdff'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='absoimgpath',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='absoimgpath'),
        ),
    ]
