# Generated by Django 2.0.1 on 2020-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0016_auto_20200811_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='absoimgpathh',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='absoimgpathh'),
        ),
        migrations.AlterField(
            model_name='ssdpatent',
            name='absoimgpath',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='摘要图'),
        ),
    ]
