# Generated by Django 2.0.1 on 2020-08-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0017_auto_20200811_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssdpatent',
            name='add',
        ),
    ]
