# Generated by Django 2.0.1 on 2020-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0018_remove_ssdpatent_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdpatent',
            name='addd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='addd日期'),
        ),
    ]
