# Generated by Django 2.0.1 on 2020-08-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdpatent', '0019_ssdpatent_addd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssdpatent',
            name='absoimgpathh',
        ),
        migrations.RemoveField(
            model_name='ssdpatent',
            name='addd',
        ),
        migrations.RemoveField(
            model_name='ssdpatent',
            name='imgnamee',
        ),
        migrations.RemoveField(
            model_name='ssdpatent',
            name='imgoo',
        ),
        migrations.RemoveField(
            model_name='ssdpatent',
            name='pdd',
        ),
        migrations.RemoveField(
            model_name='ssdpatent',
            name='pdff',
        ),
    ]
