# Generated by Django 2.0.1 on 2020-08-18 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=100, verbose_name='单位名称')),
                ('order_address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('order_contact', models.CharField(default='', max_length=100, verbose_name='联系人')),
                ('order_mobile', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('base_price', models.IntegerField(default=0, verbose_name='基础费')),
                ('serve_fee', models.IntegerField(default=0, verbose_name='服务费')),
                ('total_price', models.IntegerField(default=0, verbose_name='总费')),
                ('step', models.CharField(choices=[('-1', '已取消'), ('0', '下单未付款'), ('1', '买家已付款'), ('2', '已提交专利局'), ('3', '交易完成')], default='0', max_length=10, verbose_name='订单阶段')),
                ('contract', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='合同')),
                ('prof', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='付款凭证')),
                ('step_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='阶段时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '专利交易管理',
                'verbose_name_plural': '专利交易管理',
            },
        ),
        migrations.CreateModel(
            name='BuyerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', '等待支付定金'), ('1', '平台合同签订'), ('2', '三方协议签订'), ('3', '履约完成'), ('-1', '取消或终止')], default='0', max_length=10, verbose_name='订单阶段')),
                ('step_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='阶段时间')),
                ('contract', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='合同')),
                ('prof', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='定金凭证')),
                ('protocol', models.FileField(blank=True, default='', null=True, upload_to='protocol/resource/%Y/%m', verbose_name='协议')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '技术项目订单管理',
                'verbose_name_plural': '技术项目订单管理',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='数据ID')),
                ('fav_type', models.IntegerField(choices=[(0, '政策'), (1, '专利'), (2, '项目'), (3, '其他慢慢加')], default=1, verbose_name='数据类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户咨询',
                'verbose_name_plural': '用户咨询',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='数据ID')),
                ('fav_type', models.IntegerField(choices=[(0, '政策'), (1, '专利'), (2, '项目'), (3, '孵化器'), (4, '科技园区'), (5, '金融机构'), (6, '展会'), (7, '展会点赞')], default=1, verbose_name='数据类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_id', models.IntegerField(default=0, verbose_name='数据ID')),
                ('join_type', models.IntegerField(choices=[(0, '政策'), (1, '专利'), (2, '项目'), (3, '展会')], default=1, verbose_name='数据类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户报名',
                'verbose_name_plural': '用户报名',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='接收用户')),
                ('message', models.CharField(max_length=500, verbose_name='消息内容')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
    ]
