# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 19:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patent', '0016_auto_20181116_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0012_projectt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=100, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('order_address', models.CharField(default='', max_length=100, verbose_name='\u5730\u5740')),
                ('order_contact', models.CharField(default='', max_length=100, verbose_name='\u8054\u7cfb\u4eba')),
                ('order_mobile', models.CharField(default='', max_length=11, verbose_name='\u624b\u673a')),
                ('base_price', models.IntegerField(default=0, verbose_name='\u57fa\u7840\u8d39')),
                ('serve_fee', models.IntegerField(default=0, verbose_name='\u670d\u52a1\u8d39')),
                ('total_price', models.IntegerField(default=0, verbose_name='\u603b\u8d39')),
                ('step', models.CharField(choices=[('-1', '\u5df2\u53d6\u6d88'), ('0', '\u4e0b\u5355\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40'), ('3', '\u4ea4\u6613\u5b8c\u6210')], default='0', max_length=10, verbose_name='\u8ba2\u5355\u9636\u6bb5')),
                ('contract', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5408\u540c')),
                ('prof', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u4ed8\u6b3e\u51ed\u8bc1')),
                ('step_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u9636\u6bb5\u65f6\u95f4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent.Patent', verbose_name='\u4e13\u5229')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e1a\u52a1\u5458')),
            ],
            options={
                'verbose_name': '\u4e13\u5229\u4ea4\u6613\u7ba1\u7406',
                'verbose_name_plural': '\u4e13\u5229\u4ea4\u6613\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='BuyerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', '\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40')], default='0', max_length=10, verbose_name='\u5408\u4f5c\u9636\u6bb5')),
                ('step_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u9636\u6bb5\u65f6\u95f4')),
                ('contract', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5408\u540c')),
                ('prof', models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5b9a\u91d1\u51ed\u8bc1')),
                ('protocol', models.FileField(blank=True, default='', null=True, upload_to='protocol/resource/%Y/%m', verbose_name='\u534f\u8bae')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='\u9879\u76ee')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e1a\u52a1\u5458')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u9879\u76ee\u8ba2\u5355\u7ba1\u7406',
                'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u8ba2\u5355\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eID')),
                ('fav_type', models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5176\u4ed6\u6162\u6162\u52a0')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u54a8\u8be2',
                'verbose_name_plural': '\u7528\u6237\u54a8\u8be2',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eID')),
                ('fav_type', models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5b75\u5316\u5668'), (4, '\u79d1\u6280\u56ed\u533a'), (5, '\u91d1\u878d\u673a\u6784'), (6, '\u5c55\u4f1a'), (7, '\u5176\u4ed6')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_id', models.IntegerField(default=0, verbose_name='\u6570\u636eID')),
                ('join_type', models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5c55\u4f1a')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u62a5\u540d',
                'verbose_name_plural': '\u7528\u6237\u62a5\u540d',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6237')),
                ('message', models.CharField(max_length=500, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
    ]
