# Generated by Django 2.0.1 on 2020-08-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
        ('project', '0001_initial'),
        ('ssdpatent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='buyerproject',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AddField(
            model_name='buyerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='buyerproject',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='业务员'),
        ),
        migrations.AddField(
            model_name='buyerpatent',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AddField(
            model_name='buyerpatent',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdpatent.SSDPatent', verbose_name='专利'),
        ),
        migrations.AddField(
            model_name='buyerpatent',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='业务员'),
        ),
    ]
