# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 14:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20181019_1325'),
        ('operation', '0002_userask_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='\u9879\u76ee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9879\u76ee',
                'verbose_name_plural': '\u7528\u6237\u9879\u76ee',
            },
        ),
        migrations.RenameField(
            model_name='userpatent',
            old_name='user',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='userpatent',
            name='step',
            field=models.CharField(choices=[('0', '\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40')], default='0', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5176\u4ed6\u6162\u6162\u52a0')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='userpatent',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent.Patent', verbose_name='\u4e13\u5229'),
        ),
    ]
