# Generated by Django 2.0.1 on 2019-01-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181116_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(0, '政策'), (1, '专利'), (2, '项目'), (3, '孵化器'), (4, '科技园区'), (5, '金融机构'), (6, '展会'), (7, '展会点赞')], default=1, verbose_name='数据类别'),
        ),
    ]
