# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 15:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_project_seller'),
        ('patent', '0008_patent_seller'),
        ('operation', '0003_auto_20181019_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=100, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('order_address', models.CharField(default='', max_length=100, verbose_name='\u5730\u5740')),
                ('order_contact', models.CharField(default='', max_length=100, verbose_name='\u8054\u7cfb\u4eba')),
                ('order_mobile', models.CharField(default='', max_length=11, verbose_name='\u624b\u673a')),
                ('base_price', models.IntegerField(default=0, verbose_name='\u57fa\u7840\u8d39')),
                ('serve_fee', models.IntegerField(default=0, verbose_name='\u670d\u52a1\u8d39')),
                ('total_price', models.IntegerField(default=0, verbose_name='\u603b\u8d39')),
                ('step', models.CharField(choices=[('0', '\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40')], default='0', max_length=10, verbose_name='\u8ba2\u5355\u9636\u6bb5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent.Patent', verbose_name='\u4e13\u5229')),
            ],
            options={
                'verbose_name': '\u4e13\u5229\u4ea4\u6613\u7ba1\u7406',
                'verbose_name_plural': '\u4e13\u5229\u4ea4\u6613\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='BuyerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', '\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40')], default='0', max_length=10, verbose_name='\u5408\u4f5c\u9636\u6bb5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='\u9879\u76ee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8f6c\u6362\u7ba1\u7406',
                'verbose_name_plural': '\u9879\u76ee\u8f6c\u6362\u7ba1\u7406',
            },
        ),
        migrations.RemoveField(
            model_name='userpatent',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='userpatent',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPatent',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
