# Generated by Django 2.0.1 on 2020-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190101_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpatent',
            name='step',
            field=models.CharField(choices=[('-1', '已取消'), ('0', '下单未付款'), ('1', '买家已付款'), ('2', '已提交专利局'), ('3', '交易完成')], default='0', max_length=10, verbose_name='订单阶段'),
        ),
    ]
