# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-31 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_auto_20181019_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='policy_name',
        ),
        migrations.AddField(
            model_name='userask',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='\u6570\u636eID'),
        ),
        migrations.AddField(
            model_name='userask',
            name='fav_type',
            field=models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5176\u4ed6\u6162\u6162\u52a0')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='userask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
