# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 16:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0006_auto_20181031_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eID')),
                ('fav_type', models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5c55\u4f1a')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u62a5\u540d',
                'verbose_name_plural': '\u7528\u6237\u62a5\u540d',
            },
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5c55\u4f1a')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b'),
        ),
    ]
