# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20181114_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjoin',
            old_name='fav_id',
            new_name='join_id',
        ),
        migrations.RenameField(
            model_name='userjoin',
            old_name='fav_type',
            new_name='join_type',
        ),
    ]
