# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20181114_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpatent',
            name='step',
            field=models.CharField(choices=[('-1', '\u5df2\u53d6\u6d88'), ('0', '\u4e0b\u5355\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40'), ('2', '\u4ea4\u6613\u5b8c\u6210')], default='0', max_length=10, verbose_name='\u8ba2\u5355\u9636\u6bb5'),
        ),
    ]
