# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20181114_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpatent',
            name='step_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u9636\u6bb5\u65f6\u95f4'),
        ),
    ]
