# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_buyerpatent_step_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(0, '\u653f\u7b56'), (1, '\u4e13\u5229'), (2, '\u9879\u76ee'), (3, '\u5b75\u5316\u5668'), (4, '\u79d1\u6280\u56ed\u533a'), (5, '\u91d1\u878d\u673a\u6784'), (6, '\u5c55\u4f1a'), (7, '\u5176\u4ed6')], default=1, verbose_name='\u6570\u636e\u7c7b\u522b'),
        ),
    ]
