# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20181115_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpatent',
            name='contract',
            field=models.FileField(default='', upload_to='contract/resource/%Y/%m', verbose_name='\u5408\u540c'),
        ),
        migrations.AddField(
            model_name='buyerpatent',
            name='prof',
            field=models.FileField(default='', upload_to='contract/resource/%Y/%m', verbose_name='\u4ed8\u6b3e\u51ed\u8bc1'),
        ),
        migrations.AddField(
            model_name='buyerproject',
            name='prof',
            field=models.FileField(default='', upload_to='contract/resource/%Y/%m', verbose_name='\u5b9a\u91d1\u51ed\u8bc1'),
        ),
        migrations.AddField(
            model_name='buyerproject',
            name='step_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u9636\u6bb5\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='buyerpatent',
            name='step',
            field=models.CharField(choices=[('-1', '\u5df2\u53d6\u6d88'), ('0', '\u4e0b\u5355\u672a\u4ed8\u6b3e'), ('1', '\u5df2\u4ed8\u6b3e'), ('2', '\u5df2\u63d0\u4ea4\u4e13\u5229\u5c40'), ('3', '\u4ea4\u6613\u5b8c\u6210')], default='0', max_length=10, verbose_name='\u8ba2\u5355\u9636\u6bb5'),
        ),
    ]
