# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20181116_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpatent',
            name='contract',
            field=models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5408\u540c'),
        ),
        migrations.AlterField(
            model_name='buyerpatent',
            name='prof',
            field=models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u4ed8\u6b3e\u51ed\u8bc1'),
        ),
        migrations.AlterField(
            model_name='buyerproject',
            name='contract',
            field=models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5408\u540c'),
        ),
        migrations.AlterField(
            model_name='buyerproject',
            name='prof',
            field=models.FileField(blank=True, default='', null=True, upload_to='contract/resource/%Y/%m', verbose_name='\u5b9a\u91d1\u51ed\u8bc1'),
        ),
        migrations.AlterField(
            model_name='buyerproject',
            name='protocol',
            field=models.FileField(blank=True, default='', null=True, upload_to='protocol/resource/%Y/%m', verbose_name='\u534f\u8bae'),
        ),
    ]
