# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20181116_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpatent',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e1a\u52a1\u5458'),
        ),
        migrations.AlterField(
            model_name='buyerproject',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_staff_set', to=settings.AUTH_USER_MODEL, verbose_name='\u4e1a\u52a1\u5458'),
        ),
    ]
