# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_auto_20181116_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projectt', verbose_name='\u9879\u76ee'),
        ),
    ]
