# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 19:53
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u540d')),
                ('pic', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u4e3b\u56fe')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8be6\u60c5')),
                ('if_show', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u540d')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u9879\u76ee\u4e3b\u56fe')),
                ('status', models.CharField(choices=[('-1', '\u9a73\u56de'), ('0', '\u5ba1\u6838\u4e2d'), ('1', '\u901a\u8fc7\u5ba1\u6838')], default='1', max_length=20, verbose_name='\u4e0a\u67b6\u72b6\u6001')),
                ('note', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='\u5ba1\u6838\u610f\u89c1')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('download', models.FileField(upload_to='club/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u540d')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8be6\u60c5')),
                ('if_show', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u4fe1\u606f',
            },
        ),
    ]
