# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u5934\u6761', 'verbose_name_plural': '\u5934\u6761'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '\u6210\u5458\u7ba1\u7406', 'verbose_name_plural': '\u6210\u5458\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': '\u8d44\u6e90', 'verbose_name_plural': '\u8d44\u6e90'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '\u5206\u8282', 'verbose_name_plural': '\u5206\u8282'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u5934\u6761\u4e3b\u56fe'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='\u5934\u6761\u540d'),
        ),
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u6210\u5458\u540d'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('-1', '\u9a73\u56de'), ('0', '\u5ba1\u6838\u4e2d'), ('1', '\u901a\u8fc7\u5ba1\u6838')], default='1', max_length=20, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u8d44\u6e90\u540d'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='\u5206\u8282\u6807\u9898'),
        ),
    ]
