# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20181116_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='field',
            field=models.CharField(default='', max_length=100, verbose_name='\u884c\u4e1a\u9886\u57df'),
        ),
    ]
