# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_member_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='image/%Y/%m', verbose_name='logo'),
        ),
    ]
