# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181019_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_num',
            new_name='id_card',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='\u624b\u673a'),
        ),
    ]
