# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181101_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('reset_pwd', '\u5fd8\u8bb0\u5bc6\u7801'), ('update_mobile', '\u66f4\u65b0\u624b\u673a\u53f7')], max_length=20),
        ),
    ]
