# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181115_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank='', default='', max_length=50, verbose_name='\u59d3\u540d\uff08\u5b9e\u540d\uff09'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card',
            field=models.CharField(blank='', default='', max_length=50, verbose_name='\u8eab\u4efd\u8bc1\u53f7\uff08\u5b9e\u540d\uff09'),
        ),
    ]
