# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181116_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
    ]
