# Generated by Django 2.0.1 on 2020-08-18 20:36

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='项目名')),
                ('field_category', models.CharField(choices=[('0', '食品饮料'), ('1', '建筑建材'), ('2', '家居用品'), ('3', '轻工纺织'), ('4', '化学化工'), ('5', '新能源'), ('6', '机械'), ('7', '环保和资源'), ('8', '橡胶塑料'), ('9', '仪器仪表'), ('10', '新型材料'), ('11', '电子信息'), ('12', '医药与医疗'), ('13', '农林牧业'), ('14', '海洋开发'), ('15', '航空航天'), ('16', '采矿冶金'), ('17', '电气自动化'), ('18', '包装印刷'), ('19', '教育休闲'), ('20', '钒钛产业'), ('21', '安全防护'), ('22', '交通运输')], default='0', max_length=100, verbose_name='所属行业')),
                ('project_step', models.CharField(choices=[('0', '未知'), ('1', '实验室阶段'), ('2', '样品阶段'), ('3', '小试阶段'), ('4', '中试阶段'), ('5', '量产阶段')], default='0', max_length=100, verbose_name='成熟度')),
                ('cooperation', models.CharField(choices=[('0', '股权投资'), ('1', '技术转让'), ('2', '许可使用'), ('3', '合作开发'), ('4', '合作兴办新企业'), ('5', '其他')], default='0', max_length=100, verbose_name='合作方式')),
                ('province', models.CharField(choices=[('bj', '北京'), ('tj', '天津')], default='bj', max_length=20, verbose_name='项目所在地区')),
                ('main_pic', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='项目主图')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('bargain', models.BooleanField(default=False, verbose_name='议价')),
                ('hire', models.IntegerField(default=0, verbose_name='佣金')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词')),
                ('org', models.CharField(blank=True, choices=[('gx', '高校'), ('kyjg', '科研机构'), ('qt', '其他')], max_length=20, null=True, verbose_name='所属机构')),
                ('status', models.CharField(blank=True, choices=[('sqwjf', '授权未结费'), ('yxzs', '已下证书')], max_length=20, null=True, verbose_name='项目状态')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='详情')),
                ('shop_status', models.CharField(choices=[('-1', '已下架'), ('0', '审核中'), ('1', '已上架')], default='1', max_length=20, verbose_name='上架状态')),
                ('if_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('note', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='审核意见')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '技术项目信息',
                'verbose_name_plural': '技术项目信息',
            },
        ),
    ]
