# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-17 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u7c7b\u522b',
                'verbose_name_plural': '\u9879\u76ee\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u540d')),
                ('detail', models.TextField(verbose_name='\u9879\u76ee\u8be6\u60c5')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Category', verbose_name='\u6240\u5c5e\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u4fe1\u606f',
                'verbose_name_plural': '\u9879\u76ee\u4fe1\u606f',
            },
        ),
    ]
