# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u6280\u672f\u9879\u76ee\u4fe1\u606f', 'verbose_name_plural': '\u6280\u672f\u9879\u76ee\u4fe1\u606f'},
        ),
    ]
