# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectt',
            name='patent_category',
        ),
        migrations.RemoveField(
            model_name='projectt',
            name='patent_expired',
        ),
        migrations.RemoveField(
            model_name='projectt',
            name='patent_id',
        ),
        migrations.AddField(
            model_name='projectt',
            name='cooperation',
            field=models.CharField(choices=[('0', '\u80a1\u6743\u6295\u8d44'), ('1', '\u6280\u672f\u8f6c\u8ba9'), ('2', '\u8bb8\u53ef\u4f7f\u7528'), ('3', '\u5408\u4f5c\u5f00\u53d1'), ('4', '\u5408\u4f5c\u5174\u529e\u65b0\u4f01\u4e1a'), ('5', '\u5176\u4ed6')], default='0', max_length=100, verbose_name='\u5408\u4f5c\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='project_step',
            field=models.CharField(choices=[('0', '\u672a\u77e5'), ('1', '\u5b9e\u9a8c\u5ba4\u9636\u6bb5'), ('2', '\u6837\u54c1\u9636\u6bb5'), ('3', '\u5c0f\u8bd5\u9636\u6bb5'), ('4', '\u4e2d\u8bd5\u9636\u6bb5'), ('5', '\u91cf\u4ea7\u9636\u6bb5')], default='0', max_length=100, verbose_name='\u6210\u719f\u5ea6'),
        ),
        migrations.AlterField(
            model_name='projectt',
            name='main_pic',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u9879\u76ee\u4e3b\u56fe'),
        ),
        migrations.AlterField(
            model_name='projectt',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u540d'),
        ),
        migrations.AlterField(
            model_name='projectt',
            name='province',
            field=models.CharField(choices=[('bj', '\u5317\u4eac'), ('tj', '\u5929\u6d25')], default='bj', max_length=20, verbose_name='\u9879\u76ee\u6240\u5728\u5730\u533a'),
        ),
    ]
