# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20181116_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectt',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Projectt',
        ),
    ]
