# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20181116_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shop_status',
            field=models.CharField(choices=[('-1', '\u5df2\u4e0b\u67b6'), ('0', '\u5ba1\u6838\u4e2d'), ('1', '\u5df2\u4e0a\u67b6')], default='1', max_length=20, verbose_name='\u4e0a\u67b6\u72b6\u6001'),
        ),
    ]
