# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20181116_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.CharField(blank=True, choices=[('gx', '\u9ad8\u6821'), ('kyjg', '\u79d1\u7814\u673a\u6784'), ('qt', '\u5176\u4ed6')], max_length=20, null=True, verbose_name='\u6240\u5c5e\u673a\u6784'),
        ),
    ]
