# Generated by Django 2.0.1 on 2020-08-18 20:36

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='专利名')),
                ('patent_id', models.CharField(default='', max_length=100, verbose_name='专利申请号')),
                ('field_category', models.CharField(choices=[('0', '食品饮料'), ('1', '建筑建材'), ('2', '家居用品'), ('3', '轻工纺织'), ('4', '化学化工'), ('5', '新能源'), ('6', '机械'), ('7', '环保和资源'), ('8', '橡胶塑料'), ('9', '仪器仪表'), ('10', '新型材料'), ('11', '电子信息'), ('12', '医药与医疗'), ('13', '农林牧业'), ('14', '海洋开发'), ('15', '航空航天'), ('16', '采矿冶金'), ('17', '电气自动化'), ('18', '包装印刷'), ('19', '教育休闲'), ('20', '钒钛产业'), ('21', '安全防护'), ('22', '交通运输')], default='0', max_length=100, verbose_name='所属行业')),
                ('patent_category', models.CharField(choices=[('fmzl', '发明专利'), ('syxxzl', '实用新型专利'), ('wgzl', '外观专利')], default='fmzl', max_length=100, verbose_name='专利类别')),
                ('province', models.CharField(choices=[('bj', '北京'), ('tj', '天津')], default='bj', max_length=20, verbose_name='专利所在地区')),
                ('patent_expired', models.DateField(default=datetime.datetime.now, verbose_name='有效日期')),
                ('main_pic', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='专利主图')),
                ('more_pic', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='专利图')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('bargain', models.BooleanField(default=False, verbose_name='议价')),
                ('hire', models.IntegerField(default=0, verbose_name='佣金')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词')),
                ('status', models.CharField(blank=True, choices=[('sqwjf', '授权未结费'), ('yxzs', '已下证书')], max_length=20, null=True, verbose_name='专利状态')),
                ('IPC_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类号')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='申请日期')),
                ('agent', models.CharField(blank=True, max_length=20, null=True, verbose_name='代理人')),
                ('agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='代理机构')),
                ('inventor', models.CharField(blank=True, max_length=20, null=True, verbose_name='发明人')),
                ('applicant', models.CharField(blank=True, max_length=20, null=True, verbose_name='申请人')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人')),
                ('contact_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='详情')),
                ('shop_status', models.CharField(choices=[('-1', '已下架'), ('0', '审核中'), ('1', '已上架'), ('2', '交易中'), ('3', '已交易')], default='1', max_length=20, verbose_name='上架状态')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('note', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='审核意见')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '专利商品信息',
                'verbose_name_plural': '专利商品信息',
            },
        ),
    ]
