# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patent',
            options={'verbose_name': '\u4e13\u5229\u5546\u54c1\u4fe1\u606f', 'verbose_name_plural': '\u4e13\u5229\u5546\u54c1\u4fe1\u606f'},
        ),
    ]
