# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0002_auto_20181019_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='publish_time',
        ),
        migrations.AddField(
            model_name='patent',
            name='IPC_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5206\u7c7b\u53f7'),
        ),
        migrations.AddField(
            model_name='patent',
            name='agency',
            field=models.CharField(default='', max_length=20, verbose_name='\u4ee3\u7406\u673a\u6784'),
        ),
        migrations.AddField(
            model_name='patent',
            name='agent',
            field=models.CharField(default='', max_length=20, verbose_name='\u4ee3\u7406\u4eba'),
        ),
        migrations.AddField(
            model_name='patent',
            name='applicant',
            field=models.CharField(default='', max_length=20, verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AddField(
            model_name='patent',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7533\u8bf7\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='patent',
            name='bargain',
            field=models.BooleanField(default=False, verbose_name='\u8bae\u4ef7'),
        ),
        migrations.AddField(
            model_name='patent',
            name='contact',
            field=models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='patent',
            name='contact_mobile',
            field=models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='patent',
            name='field_category',
            field=models.CharField(choices=[('0', '\u98df\u54c1\u996e\u6599'), ('1', '\u5efa\u7b51\u5efa\u6750'), ('2', '\u5bb6\u5c45\u7528\u54c1'), ('3', '\u8f7b\u5de5\u7eba\u7ec7'), ('4', '\u5316\u5b66\u5316\u5de5'), ('5', '\u65b0\u80fd\u6e90'), ('6', '\u673a\u68b0'), ('7', '\u73af\u4fdd\u548c\u8d44\u6e90'), ('8', '\u6a61\u80f6\u5851\u6599'), ('9', '\u4eea\u5668\u4eea\u8868'), ('10', '\u65b0\u578b\u6750\u6599'), ('11', '\u7535\u5b50\u4fe1\u606f'), ('12', '\u533b\u836f\u4e0e\u533b\u7597'), ('13', '\u519c\u6797\u7267\u4e1a'), ('14', '\u6d77\u6d0b\u5f00\u53d1'), ('15', '\u822a\u7a7a\u822a\u5929'), ('16', '\u91c7\u77ff\u51b6\u91d1'), ('17', '\u7535\u6c14\u81ea\u52a8\u5316'), ('18', '\u5305\u88c5\u5370\u5237'), ('19', '\u6559\u80b2\u4f11\u95f2'), ('20', '\u9492\u949b\u4ea7\u4e1a'), ('21', '\u5b89\u5168\u9632\u62a4'), ('22', '\u4ea4\u901a\u8fd0\u8f93')], default='0', max_length=100, verbose_name='\u6240\u5c5e\u884c\u4e1a'),
        ),
        migrations.AddField(
            model_name='patent',
            name='hire',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4f63\u91d1'),
        ),
        migrations.AddField(
            model_name='patent',
            name='inventor',
            field=models.CharField(default='', max_length=20, verbose_name='\u53d1\u660e\u4eba'),
        ),
        migrations.AddField(
            model_name='patent',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='patent',
            name='main_pic',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='\u4e13\u5229\u4e3b\u56fe'),
        ),
        migrations.AddField(
            model_name='patent',
            name='more_pic',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='\u4e13\u5229\u56fe'),
        ),
        migrations.AddField(
            model_name='patent',
            name='patent_category',
            field=models.CharField(choices=[('fmzl', '\u53d1\u660e\u4e13\u5229'), ('syxxzl', '\u5b9e\u7528\u65b0\u578b\u4e13\u5229'), ('wgzl', '\u5916\u89c2\u4e13\u5229')], default='fmzl', max_length=100, verbose_name='\u4e13\u5229\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='patent',
            name='patent_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='patent',
            name='patent_id',
            field=models.CharField(default='', max_length=100, verbose_name='\u4e13\u5229\u7533\u8bf7\u53f7'),
        ),
        migrations.AddField(
            model_name='patent',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AddField(
            model_name='patent',
            name='province',
            field=models.CharField(choices=[('bj', '\u5317\u4eac'), ('tj', '\u5929\u6d25')], default='bj', max_length=20, verbose_name='\u4e13\u5229\u6240\u5728\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u4e13\u5229\u540d'),
        ),
    ]
