# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0004_auto_20181019_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='status',
            field=models.CharField(blank=True, choices=[('sqwjf', '\u6388\u6743\u672a\u7ed3\u8d39'), ('yxzs', '\u5df2\u4e0b\u8bc1\u4e66')], max_length=20, null=True, verbose_name='\u4e13\u5229\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_expired',
            field=models.DateField(blank=True, null=True, verbose_name='\u6709\u6548\u65e5\u671f'),
        ),
    ]
