# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0005_auto_20181019_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patent_expired',
            field=models.DateField(default=datetime.datetime.now, verbose_name='\u6709\u6548\u65e5\u671f'),
        ),
    ]
