# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0006_auto_20181019_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u7533\u8bf7\u65e5\u671f'),
        ),
    ]
