# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 19:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0008_patent_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u8be6\u60c5'),
        ),
    ]
