# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0010_patent_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='shop_status',
            field=models.CharField(choices=[('-1', '\u5df2\u4e0b\u67b6'), ('0', '\u5ba1\u6838\u4e2d'), ('1', '\u5df2\u4e0a\u67b6'), ('2', '\u5df2\u4ea4\u6613')], default='1', max_length=20, verbose_name='\u4e0a\u67b6\u72b6\u6001'),
        ),
    ]
