# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0014_patent_if_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
