# Generated by Django 2.0.1 on 2020-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couveuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='孵化器名字')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='所在地0')),
                ('area1', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地1')),
                ('pic', models.ImageField(default='image/incubator.png', upload_to='image/%Y/%m', verbose_name='主图')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='级别')),
                ('url_introduce', models.CharField(blank=True, max_length=100, null=True, verbose_name='介绍链接')),
                ('url_companys', models.CharField(blank=True, max_length=100, null=True, verbose_name='孵化企业链接')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('companys', models.TextField(blank=True, null=True, verbose_name='孵化企业')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮编')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '孵化器库',
                'verbose_name_plural': '孵化器库',
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='金融机构名称')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='所在地0')),
                ('area1', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地1')),
                ('pic', models.ImageField(default='image/incubator.png', upload_to='image/%Y/%m', verbose_name='主图')),
                ('url_introduce', models.CharField(blank=True, max_length=100, null=True, verbose_name='介绍链接')),
                ('url_services', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务链接')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='机构类型')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('services', models.TextField(blank=True, null=True, verbose_name='产品服务')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮编')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '金融服务',
                'verbose_name_plural': '金融服务',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='园区名字')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='所在地0')),
                ('area1', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地1')),
                ('pic', models.ImageField(default='image/incubator.png', upload_to='image/%Y/%m', verbose_name='主图')),
                ('url_introduce', models.CharField(blank=True, max_length=100, null=True, verbose_name='介绍链接')),
                ('url_techservice', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务链接')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('techservice', models.TextField(blank=True, null=True, verbose_name='服务')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮编')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '高新园区',
                'verbose_name_plural': '高新园区',
            },
        ),
        migrations.CreateModel(
            name='YellowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='机构名称')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='所在地0')),
                ('area1', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地1')),
                ('org', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门')),
                ('addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('website', models.CharField(blank=True, max_length=300, null=True, verbose_name='网址')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '黄页',
                'verbose_name_plural': '黄页',
            },
        ),
    ]
