# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4e13\u5bb6\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u4e13\u5bb6\u63cf\u8ff0')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('filed', models.CharField(max_length=30, verbose_name='\u4e13\u4e1a\u9886\u57df')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u4e13\u5bb6\u4fe1\u606f',
                'verbose_name_plural': '\u4e13\u5bb6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u673a\u6784\u63cf\u8ff0')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('address', models.CharField(max_length=150, verbose_name='\u673a\u6784\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u6784\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='Organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incubator.Organization', verbose_name='\u6240\u5c5e\u7c7b\u522b'),
        ),
    ]
