# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20180923_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couveuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b75\u5316\u5668\u540d\u5b57')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57300')),
                ('area1', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57301')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7ea7\u522b')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('gen_firm', models.TextField(blank=True, null=True, verbose_name='\u5728\u5b75\u4f01\u4e1a')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7f16')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5730\u5740')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='\u662f\u5426\u63a8\u8350')),
            ],
            options={
                'verbose_name': '\u5b75\u5316\u5668\u5e93',
                'verbose_name_plural': '\u5b75\u5316\u5668\u5e93',
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u91d1\u878d\u673a\u6784\u540d\u79f0')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57300')),
                ('area1', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57301')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u673a\u6784\u7c7b\u578b')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('service', models.TextField(blank=True, null=True, verbose_name='\u4ea7\u54c1\u670d\u52a1')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7f16')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5730\u5740')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='\u662f\u5426\u63a8\u8350')),
            ],
            options={
                'verbose_name': '\u91d1\u878d\u670d\u52a1',
                'verbose_name_plural': '\u91d1\u878d\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56ed\u533a\u540d\u5b57')),
                ('area0', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57300')),
                ('area1', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57301')),
                ('descs', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('service', models.TextField(blank=True, null=True, verbose_name='\u79d1\u6280\u670d\u52a1')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
                ('contact_post', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7f16')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5730\u5740')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='\u662f\u5426\u63a8\u8350')),
            ],
            options={
                'verbose_name': '\u9ad8\u65b0\u56ed\u533a',
                'verbose_name_plural': '\u9ad8\u65b0\u56ed\u533a',
            },
        ),
    ]
