# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0003_couveuse_financial_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='couveuse',
            name='url_companys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b75\u5316\u9875\u9762'),
        ),
        migrations.AddField(
            model_name='couveuse',
            name='url_introduce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4ecb\u7ecd\u9875\u9762'),
        ),
    ]
