# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-08 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_auto_20181108_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='type',
        ),
    ]
