# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0007_auto_20181108_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='Organization',
        ),
        migrations.AddField(
            model_name='couveuse',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='financial',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='park',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570'),
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
