# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0008_auto_20181115_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5730\u5740')),
                ('website', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7f51\u5740')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
            ],
            options={
                'verbose_name': '\u9ec4\u9875',
                'verbose_name_plural': '\u9ec4\u9875',
            },
        ),
    ]
