# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0009_yellowpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowpage',
            name='area0',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6240\u5728\u57300'),
        ),
        migrations.AddField(
            model_name='yellowpage',
            name='area1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6240\u5728\u57301'),
        ),
        migrations.AddField(
            model_name='yellowpage',
            name='org',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='yellowpage',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u94fe\u63a5'),
        ),
    ]
