# Generated by Django 2.0.1 on 2020-08-18 20:36

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='活动名字')),
                ('pic', models.ImageField(default='image/incubator.png', upload_to='image/%Y/%m', verbose_name='主图')),
                ('descs', DjangoUeditor.models.UEditorField(default='', verbose_name='详情')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('time_begin', models.DateTimeField(default=datetime.datetime.now, verbose_name='活动开始日期')),
                ('time_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='活动结束日期')),
                ('status', models.CharField(max_length=50, verbose_name='活动状态')),
                ('type', models.CharField(choices=[('0', '线上活动'), ('1', '线下活动')], default='0', max_length=10, verbose_name='活动类型')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('join_num', models.IntegerField(default=0, verbose_name='报名人数')),
                ('if_recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '展会平台',
                'verbose_name_plural': '展会平台',
            },
        ),
    ]
