# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 18:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181114_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='descs',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u8be6\u60c5'),
        ),
    ]
